# Generated by Django 4.2.2 on 2023-07-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=122)),
                ('LastName', models.CharField(max_length=122)),
                ('Username', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('reason', models.TextField()),
            ],
        ),
    ]
