# Generated by Django 4.2.2 on 2023-07-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_contact_delete_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
    ]
