# Generated by Django 4.2.2 on 2023-07-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_rename_contact_contacts'),
    ]

    operations = [
    ]
